### ISSUE TITLE
BUG: TypeError: run must be a Run (was <class 'neptune.new.handler.Handler'>)

### ISSUE THREAD

**Issue by DhruvilKarani** [neptune-ai/neptune-optuna#12]
### Describe the bug

Creating Neptune-optuna callback in a kedro node with `neptune_run`  as one of the parameters raises the above error. Likely due to the recent fix in [#32](https://github.com/neptune-ai/kedro-neptune/issues/32).

### Reproduction

The snippet `neptune_callback = optuna_utils.NeptuneCallback(neptune_run)` in 

```
def train_model(df_train, y_label, features, neptune_run:  neptune.handler.Handler):
    X_train = df_train[features].values
    y_train = df_train[y_label].values

    def objective(trial):
        n_estimators = trial.suggest_int('n_estimators', 2, 50)
        max_depth = int(trial.suggest_loguniform('max_depth', 1, 20))
        model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth)
        return cross_val_score(model, X_train, y_train, 
            n_jobs=-1, cv=5).mean()

    study = optuna.create_study(direction='maximize')
    neptune_callback = optuna_utils.NeptuneCallback(neptune_run)
    study.optimize(objective, n_trials=100, callbacks=[neptune_callback])
    model = RandomForestClassifier(**study.best_params)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_train)
    acc = accuracy_score(y_train, y_pred)
    neptune_run['nodes/report/train_accuracy'] = acc
    fig, ax = plt.subplots()
    plot_confusion_matrix(y_train, y_pred, ax=ax)
    neptune_run['nodes/report/train_confusion_matrix'].upload(fig)
    return model, {"acc":acc}, {"features":features, "model_type": "RandomForest"}
```
Raises the error

### Traceback

```
Traceback (most recent call last):
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 246, in main
    cli_collection()
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 189, in main
    **extra,
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/kedro/framework/cli/project.py", line 399, in run
    pipeline_name=pipeline,
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/kedro/framework/session/session.py", line 391, in run
    run_result = runner.run(filtered_pipeline, catalog, run_id)
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/kedro/runner/runner.py", line 79, in run
    self._run(pipeline, catalog, run_id)
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/kedro/runner/sequential_runner.py", line 63, in _run
    run_node(node, catalog, self._is_async, run_id)
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/kedro/runner/runner.py", line 192, in run_node
    node = _run_node_sequential(node, catalog, run_id)
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/kedro/runner/runner.py", line 281, in _run_node_sequential
    outputs = _call_node_run(node, catalog, inputs, is_async, run_id=run_id)
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/kedro/runner/runner.py", line 249, in _call_node_run
    raise exc
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/kedro/runner/runner.py", line 239, in _call_node_run
    outputs = node.run(inputs)
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/kedro/pipeline/node.py", line 451, in run
    raise exc
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/kedro/pipeline/node.py", line 442, in run
    outputs = self._run_with_list(inputs, self._inputs)
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/kedro/pipeline/node.py", line 482, in _run_with_list
    return self._decorated_func(*(inputs[item] for item in node_inputs))
  File "/Users/dhruvilkarani/Desktop/neptune/kedro-blog/tutorial/src/tutorial/pipelines/data_science/nodes.py", line 32, in train_model
    neptune_callback = optuna_utils.NeptuneCallback(neptune_run)
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/neptune_optuna/impl/__init__.py", line 120, in __init__
    verify_type('run', run, neptune.Run)
  File "/Users/dhruvilkarani/opt/anaconda3/envs/blog/lib/python3.7/site-packages/neptune/new/internal/utils/__init__.py", line 47, in verify_type
    "{} must be a {} (was {})".format(var_name, type_name, type(var))
TypeError: run must be a Run (was <class 'neptune.new.handler.Handler'>)
```

### Additional context
Environment and other details are the same as mentioned in [#32](https://github.com/neptune-ai/kedro-neptune/issues/32)

**Comment by kamil-kaczmarek** [comment]
@Raalsky , can you have a look at this?

**Comment by kamil-kaczmarek** [comment]
Hey @DhruvilKarani ,

Thanks for reporting this. I took a closer look at your code and error, here is my suggestion:

Optuna callback expects "run" to be object: `neptune.Run` not Handler. This is why you have TypeError.

Try to pass `neptune_run` that is a Run object, basically what `neptune.init` method returns.

**Remark**
If you create `neptune_run` like this:
```
run = neptune.init(...)
neptune_run = run["my_hpo"]
```

You have the error as shown above, as optuna expect Run object while you passed Handler object.

To solve this, you can create optuna callback like this:
```
import neptune.new.integrations.optuna as optuna_utils

run = neptune.init(...)
neptune_callback = optuna_utils.NeptuneCallback(run=run, base_namespace="my_hpo")
```

For this you will need to update:
```
def train_model(df_train, y_label, features, neptune_run: neptune.Run, base_namespace: str)
```

Hope this helps!

cc: @Raalsky

**Comment by Blaizzy** [comment]
Hi @DhruvilKarani,

Prince Canuma here Data Scientist at Neptune.ai

@DhruvilKarani can you instead of using `neptune.handler.Handler` use `neptune.run.Handler` and let me if it works for you? 

Docs: https://docs.neptune.ai/integrations-and-supported-tools/automation-pipelines/kedro#step-3-add-neptune-logging-to-a-kedro-node

**Comment by Blaizzy** [comment]
**Stale issue** - closing.

**Comment by Blaizzy** [comment]
Hey @DhruvilKarani 

I was wrong here, I'm sorry. From working on this [issue](https://github.com/neptune-ai/kedro-neptune/issues/46) I now understand the problem is much deeper.

You wanted to use two integrations that take different object types. **Kedro integration** takes [`Handler`](https://docs.neptune.ai/api-reference/field-types#namespace-handler) object (specific namespace or field), and the **Optuna integration** takes a [`Run`](https://docs.neptune.ai/api-reference/run) object (parent of multiple `Handlers` and the representation of all metadata that you log to Neptune)

You can access the `Run` object from the `Handler` object using that `container` property.

```
...
neptune_callback = optuna_utils.NeptuneCallback(neptune_run.container)
```

We have an example here:
https://github.com/neptune-ai/kedro-neptune/blob/main/examples/planets/src/planets/pipelines/moons_classifier.py#L97


Please let me know if this works for you.
