### ISSUE TITLE
ValueError when first trial doesn't finish

### ISSUE THREAD

**Issue by saiden89** [neptune-ai/neptune-optuna#4]
Sometimes the first Optuna trial doesn't finish, possibly because it gets pruned or, as in the following example, when an exception gets caught. In this case, Optuna can still recover, but the callback is unable to continue.
Package versions:
```
neptune-client                0.9.18
neptune-optuna                0.9.12
optuna                        2.8.0

```

Steps to reproduce:
```python3
import torch
import optuna
import neptune.new.integrations.optuna as optuna_utils
import neptune.new as neptune

class Heavy(torch.nn.Module):
    def __init__(self, trial):
        super(Heavy, self).__init__()
        n = trial.suggest_int('n_layers', 4000, 4001)
        layers = list()
        layers = [torch.nn.Linear(1000, 1000) for i in range(n)]
        self.mlp = torch.nn.Sequential(*layers)
        
    def forward(self, x):
        return self.mlp(x)
    
def objective(trial):
    model = Heavy(trial).to('cuda')
    x = torch.rand((1,1000), dtype=torch.float).to('cuda')
    return 0.5

run = neptune.init(api_token='ANONYMOUS', project='common/optuna-integration', mode='debug')
neptune_callback = optuna_utils.NeptuneCallback(run)
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=50,
               catch=(RuntimeError,),
               callbacks=[neptune_callback]
              )
```

Output:
```python3
[I 2021-06-18 20:38:07,380] A new study created in memory with name: no-name-6b1315ae-c981-48e3-98f0-7d45ce0eb6c2
[W 2021-06-18 20:40:25,359] Trial 0 failed because of the following error: RuntimeError('CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 15.78 GiB total capacity; 14.64 GiB already allocated; 7.19 MiB free; 14.64 GiB reserved in total by PyTorch)')
Traceback (most recent call last):
  File ".conda/envs/pytorch/lib/python3.8/site-packages/optuna/_optimize.py", line 216, in _run_trial
    value_or_values = func(trial)
  File "<ipython-input-1-f1a4090d39d8>", line 18, in objective
    model = Heavy(trial).to('cuda')
  File ".conda/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File ".conda/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File ".conda/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File ".conda/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File ".conda/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 15.78 GiB total capacity; 14.64 GiB already allocated; 7.19 MiB free; 14.64 GiB reserved in total by PyTorch)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-f1a4090d39d8> in <module>
     23 neptune_callback = optuna_utils.NeptuneCallback(run)
     24 study = optuna.create_study(direction="minimize")
---> 25 study.optimize(objective, n_trials=50,
     26                catch=(RuntimeError,),
     27                callbacks=[neptune_callback]

.conda/envs/pytorch/lib/python3.8/site-packages/optuna/study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    399             )
    400 
--> 401         _optimize(
    402             study=self,
    403             func=func,

.conda/envs/pytorch/lib/python3.8/site-packages/optuna/_optimize.py in _optimize(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
     63     try:
     64         if n_jobs == 1:
---> 65             _optimize_sequential(
     66                 study,
     67                 func,

.conda/envs/pytorch/lib/python3.8/site-packages/optuna/_optimize.py in _optimize_sequential(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)
    174             frozen_trial = copy.deepcopy(study._storage.get_trial(trial._trial_id))
    175             for callback in callbacks:
--> 176                 callback(study, frozen_trial)
    177 
    178         if progress_bar is not None:

.conda/envs/pytorch/lib/python3.8/site-packages/neptune_optuna/impl/__init__.py in __call__(self, study, trial)
    148         self._log_trial(trial)
    149         self._log_trial_distributions(trial)
--> 150         self._log_best_trials(study)
    151         self._log_study_details(study, trial)
    152         self._log_plots(study, trial)

.conda/envs/pytorch/lib/python3.8/site-packages/neptune_optuna/impl/__init__.py in _log_best_trials(self, study)
    160 
    161     def _log_best_trials(self, study):
--> 162         self.run['best'] = _stringify_keys(_log_best_trials(study))
    163 
    164     def _log_study_details(self, study, trial):

.conda/envs/pytorch/lib/python3.8/site-packages/neptune_optuna/impl/__init__.py in _log_best_trials(study)
    420 
    421 def _log_best_trials(study: optuna.Study):
--> 422     best_results = {'value': study.best_value,
    423                     'params': study.best_params,
    424                     'value|params': f'value: {study.best_value}| params: {study.best_params}'}

.conda/envs/pytorch/lib/python3.8/site-packages/optuna/study.py in best_value(self)
     73         """
     74 
---> 75         best_value = self.best_trial.value
     76         assert best_value is not None
     77 

.conda/envs/pytorch/lib/python3.8/site-packages/optuna/study.py in best_trial(self)
     96             )
     97 
---> 98         return copy.deepcopy(self._storage.get_best_trial(self._study_id))
     99 
    100     @property

.conda/envs/pytorch/lib/python3.8/site-packages/optuna/storages/_in_memory.py in get_best_trial(self, study_id)
    309             best_trial_id = self._studies[study_id].best_trial_id
    310             if best_trial_id is None:
--> 311                 raise ValueError("No trials are completed yet.")
    312             elif len(self._studies[study_id].directions) > 1:
    313                 raise ValueError(

ValueError: No trials are completed yet.
```

**Comment by Raalsky** [comment]
Hey @saiden89

Thanks for Your report. Good point actually :wink:. I agree that it should pass. Stay tuned for an update in a few following days :wink:

Rafał

**Comment by Raalsky** [comment]
@saiden89 We already released a new version (`0.9.13`) of Neptune integration for Optuna. Let us know if it fulfill your use case :wink:

**Comment by saiden89** [comment]
Yes, now the callback is able to let specified exceptions pass. I have some other bugs to report though, should I open a new issue? :smile:

**Comment by Raalsky** [comment]
I will be grateful if you would like to open a new Issue :wink:

**Comment by saiden89** [comment]
I'd like to reopen the issue. As per #5, `neptune-optuna` is now capable to letting pass specified exceptions. However, if the exception occurs on the first trial, it is impossible to recover and the study fails.
Code to reproduce:
```python3
import torch
import optuna
import random
import neptune.new.integrations.optuna as optuna_utils
import neptune.new as neptune

def objective(trial):
    2/0 #Can't divide by zero!
    return random.random()

run = neptune.init(api_token='ANONYMOUS', project='common/optuna-integration', mode='debug')
neptune_callback = optuna_utils.NeptuneCallback(run)
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=5,
               catch=(ZeroDivisionError,),
               callbacks=[neptune_callback]
              )
```
<details>
<summary> Traceback </summary>

```python3
[I 2021-07-06 15:06:27,228] A new study created in memory with name: no-name-3b69555b-94d5-4135-a4d8-cd794ed6be7a
[W 2021-07-06 15:06:27,230] Trial 0 failed because of the following error: ZeroDivisionError('division by zero')
Traceback (most recent call last):
  File ".conda/envs/pytorch/lib/python3.9/site-packages/optuna/_optimize.py", line 216, in _run_trial
    value_or_values = func(trial)
  File "/scratch/32809031/ipykernel_37826/323447056.py", line 20, in objective
    2/0
ZeroDivisionError: division by zero
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/scratch/32809031/ipykernel_37826/323447056.py in <module>
     24 neptune_callback = optuna_utils.NeptuneCallback(run)
     25 study = optuna.create_study(direction="minimize")
---> 26 study.optimize(objective, n_trials=5,
     27                catch=(ZeroDivisionError,),
     28                callbacks=[neptune_callback]

.conda/envs/pytorch/lib/python3.9/site-packages/optuna/study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    399             )
    400 
--> 401         _optimize(
    402             study=self,
    403             func=func,

.conda/envs/pytorch/lib/python3.9/site-packages/optuna/_optimize.py in _optimize(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
     63     try:
     64         if n_jobs == 1:
---> 65             _optimize_sequential(
     66                 study,
     67                 func,

.conda/envs/pytorch/lib/python3.9/site-packages/optuna/_optimize.py in _optimize_sequential(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)
    174             frozen_trial = copy.deepcopy(study._storage.get_trial(trial._trial_id))
    175             for callback in callbacks:
--> 176                 callback(study, frozen_trial)
    177 
    178         if progress_bar is not None:

.conda/envs/pytorch/lib/python3.9/site-packages/neptune_optuna/impl/__init__.py in __call__(self, study, trial)
    148         self._log_trial(trial)
    149         self._log_trial_distributions(trial)
--> 150         self._log_best_trials(study)
    151         self._log_study_details(study, trial)
    152         self._log_plots(study, trial)

.conda/envs/pytorch/lib/python3.9/site-packages/neptune_optuna/impl/__init__.py in _log_best_trials(self, study)
    160 
    161     def _log_best_trials(self, study):
--> 162         self.run['best'] = _stringify_keys(_log_best_trials(study))
    163 
    164     def _log_study_details(self, study, trial):

.conda/envs/pytorch/lib/python3.9/site-packages/neptune_optuna/impl/__init__.py in _log_best_trials(study)
    420 
    421 def _log_best_trials(study: optuna.Study):
--> 422     best_results = {'value': study.best_value,
    423                     'params': study.best_params,
    424                     'value|params': f'value: {study.best_value}| params: {study.best_params}'}

.conda/envs/pytorch/lib/python3.9/site-packages/optuna/study.py in best_value(self)
     73         """
     74 
---> 75         best_value = self.best_trial.value
     76         assert best_value is not None
     77 

.conda/envs/pytorch/lib/python3.9/site-packages/optuna/study.py in best_trial(self)
     96             )
     97 
---> 98         return copy.deepcopy(self._storage.get_best_trial(self._study_id))
     99 
    100     @property

.conda/envs/pytorch/lib/python3.9/site-packages/optuna/storages/_in_memory.py in get_best_trial(self, study_id)
    309             best_trial_id = self._studies[study_id].best_trial_id
    310             if best_trial_id is None:
--> 311                 raise ValueError("No trials are completed yet.")
    312             elif len(self._studies[study_id].directions) > 1:
    313                 raise ValueError(

ValueError: No trials are completed yet.
```
</details>
